language: node_js
cache:
 directories:
 - node_modules
notifications:
 email: false
node_js:
- '7'
- '6'
branches:
 except:
 - /^v\d+\.\d+\.\d+$/
env:
  global:
    secure: sO/llUGVY+/mx8VFCI49c2ysqegGie8FdQ1T9g/I3N+IzUQZYBFhcCSsyKxPV8oc4QJDB9m91kLidiHmJxAsTeSYXUpcVpHRDf5X31lrSFiZAJsbM9qzvD7I9cdBKE3pHxJh0UFIOqrS6NchjmksEKdzofq0EQd0NizDQQCZMJb3dMda6aDmQI+cMX/JT/BO0S5CCooqBpxn39KpsgsYThFbJQvZJFdZSlGRCWJzitN1xxtorW3du5G6aFdY3uuqqqO/7OpTND9eKhYYyAlscTN+CPlEE1TwxIGIJ9KoCvrT+tdm/nn4Czo2Oi+niA/zh51Se7P2NS7w618EliHHwPHeJ27rpbo7MJRuocB5KWi2KesVX4MlxgmH7NMZptLYdrAioGPCtCUCQfzkvZy+i2ILH24W7FruB4GrTdL3rV4mISn2jgPQfieqAjSryMyJ631WQcAUr8RVqWI4aoSv41SrC6mriNJzYBkeShpdTI3s9JDR2PpyDm9uvXDZofd24rpMxyOxI/Ou/nEH4Wpw50o2McWwgwCLLAfC1/gaqTTD/cO2aR3nQzej4dtoinqb7VF48XOEgIfRGP4PVYiwgnR4gNsXgJlpJKVRG1GvFkF536Bj2mox5A9GK5LjNsL2m1jxjy6D7W1HAokRVFyX9lGMkO6gs8vgrPv19A3/To8=
